---
- name: does the google apt file exist?
  command: test -f {{ chrome.apt_file }}
  register: google_apt_exists
  ignore_errors: True

- name: add google chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: add google chrome repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{ chrome.apt_file }} owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: update apt cache
  apt: update_cache=yes
  when: google_apt_exists.rc == 1

- name: install google chrome
  apt: pkg=google-chrome-stable state=installed

- name: allow file acces & disable web security
  lineinfile: "dest=/usr/share/applications/google-chrome.desktop state=present \
        regexp='^Exec=/usr/bin/google-chrome-stable %U' \
        line='Exec=/usr/bin/google-chrome-stable --allow-file-access-from-files --disable-web-security'"